version: '3'
services:
  backend:
    build:
      context: ./innvestigate-gui
      dockerfile: Dockerfile
    ports:
      - '8000:5000'
    volumes:
      - ./innvestigate-gui:/innvestigate-gui
      - shared_data:/frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - shared_data:/frontend

volumes:
  shared_data:
